services:
  - type: web
    name: horoscope-website
    runtime: python
    repo: https://github.com/JapaneseGerman/horoscope-website
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app